# Используем официальный образ Eclipse Temurin с Java 17
FROM eclipse-temurin:17-jdk-alpine

# Указываем, какой порт открывает контейнер
EXPOSE 8081

# Копируем собранный jar-файл в контейнер
COPY build/libs/*.jar app.jar

# Команда запуска приложения
ENTRYPOINT ["java", "-jar", "/app.jar"]